# Generated by Django 2.2.4 on 2019-09-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mainclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.MainClass')),
                ('mail_from', models.EmailField(max_length=254, verbose_name='Отправитель/От кого')),
                ('mail_to', models.EmailField(blank=True, default='admin@site.ru', max_length=254, verbose_name='Получатель/Кому')),
                ('note', models.TextField(verbose_name='Текст сообщения')),
                ('is_read', models.BooleanField(blank=True, default=False, verbose_name='Прочитано')),
                ('mail_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения пользоватлеей',
                'ordering': ('-mail_date', 'mail_from'),
            },
            bases=('accounts.mainclass',),
        ),
    ]
